extends:
  - eslint:recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins:
  - jest
  - '@typescript-eslint'
env:
  es6: true
  browser: true
  node: true
  'jest/globals': true
rules:
  no-unused-vars: [0]
  no-useless-escape: [1]
  no-constant-condition: [2, { checkLoops: false }]
  no-var: 'error'
  prefer-const: 'error'
  no-console: [0]
  no-empty-pattern: [0]
