root: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - jest
  - react
  - '@typescript-eslint'
env:
  es2021: true
  browser: true
  node: true
  jest: true
settings:
  react:
    version: 'detect'
rules:
  no-unused-vars: 'off'
  no-useless-escape: 'warn'
  no-constant-condition: ['error', { checkLoops: false }]
  no-var: 'error'
  prefer-const: 'error'
  no-console: 'off'
  no-empty-pattern: 'off'
  no-restricted-syntax:
    [
      'error',
      { 'selector': 'TSEnumDeclaration', 'message': "Don't declare enums" },
    ]
  'react/prop-types': 'off'
  'react/display-name': 'off'
overrides:
  - files: ["**/*.ts", "**/*.tsx"]
    rules:
      'no-undef': 'off'
  - files: packages/circus-web-ui/src/**/*.{js,ts,tsx}
    plugins:
      - react-hooks
    rules:
      'react-hooks/rules-of-hooks': 'error'
      'react-hooks/exhaustive-deps': 'error'
      'react/jsx-closing-bracket-location': ['error', 'line-aligned']
