@extends('common.layout')
@section('content')
<script type="text/javascript">
	$(function() {
		$('.link_group_input').click(function(){
			//Get the form ID to be sent
			var post_data = '{"btnBack":"btnBack"}';
			post_data = JSON.parse(post_data);

			var target_elm = $('.frm_group_input');

			$.ajax({
				url: "{{asset('/admin/group/input')}}",
				type: 'POST',
				data: post_data,
				dataType: 'json',
				error: function(){
					alert('I failed to communicate.');
				},
				success: function(res){
					target_elm.empty();
					target_elm.append(res.response);
					target_elm.attr('style', 'display:inline;');
				}
			});
			return false;
		});

		//Processing at the time of registration button is pressed
		$('.group_complete').click(function(){
			var post_data = $('.frm_group_complete').serializeArray();
			var target_elm = $('.frm_group_input');

			$.ajax({
				url: "{{asset('/admin/group/complete')}}",
				type: 'POST',
				data: post_data,
				dataType: 'json',
				error: function(){
					alert('I failed to communicate.');
				},
				success: function(res){
					target_elm.empty();
					target_elm.append(res.response);
					target_elm.attr('style', 'display:inline;');
				}
			});
			return false;
		});
	});
</script>
<div class="page_unique">
	<h1 class="page_ttl">{{$title}}</h1>
	{{Form::open(['url' => '', 'method' => 'post', 'class' => 'frm_group_complete'])}}
		<table class="common_table mar_b_20">
			<colgroup>
				<col width="20%">
				<col width="80%">
			</colgroup>
			<tr>
				<th>Group ID</th>
				<td>
					{{$inputs['GroupID']}}
					<span class="font_red">(ID is automatically generated by the system side)</span>
				</td>
			</tr>
			<tr>
				<th>Group Name</th>
				<td>{{$inputs['GroupName']}}</td>
			</tr>
		</table>
		<h2 class="con_ttl">Admin Role</h2>
		<table class="common_table al_l">
			<colgroup>
				<col width="20%">
				<col width="80%">
			</colgroup>
			<tbody>
				<tr>
					<th>Create Project</th>
					<td>
						@if (isset($inputs['priviledges_createProject']) && $inputs['priviledges_createProject'] == 1)
							Yes
						@else
							No
						@endif
					</td>
				</tr>
				<tr>
					<th>Create Case</th>
					<td>
						@if (isset($inputs['priviledges_createCase']) && $inputs['priviledges_createCase'] == 1)
							Yes
						@else
							No
						@endif
					</td>
				</tr>
			</tbody>
		</table>
		<p class="submit_area">
			{{Form::button('Back to Edit', array('class' => 'common_btn link_group_input'))}}
			{{Form::button('Save', array('class' => 'common_btn group_complete'))}}
		</p>
	{{Form::close()}}
	{{Form::open(['url' => asset('admin/group/input'), 'method' => 'POST', 'class' => 'frm_back'])}}
		{{Form::hidden('btnBack', 'btnBack')}}
	{{Form::close()}}
</div>
@stop