@extends('common.layout')
@section('content')
<script type="text/javascript" src="{{asset('/js/ajax/group.js')}}"></script>
<div class="page_unique">
	<h1 class="page_ttl">{{$title}}</h1>
	{{Form::open(['url' => '', 'method' => 'post', 'class' => 'frm_group_complete'])}}
		<table class="common_table mar_b_20">
			<colgroup>
				<col width="20%">
				<col width="80%">
			</colgroup>
			<tr>
				<th>Group ID</th>
				<td>
					{{$inputs['GroupID']}}
					<span class="font_red">(ID is automatically generated by the system side)</span>
				</td>
			</tr>
			<tr>
				<th>Group Name</th>
				<td>{{$inputs['GroupName']}}</td>
			</tr>
		</table>
		<h2 class="con_ttl">Admin Role</h2>
		<table class="common_table al_l">
			<colgroup>
				<col width="20%">
				<col width="80%">
			</colgroup>
			<tbody>
				<tr>
					<th>Create Project</th>
					<td>
						@if (isset($inputs['priviledges_createProject']) && $inputs['priviledges_createProject'] == 1)
							Yes
						@else
							No
						@endif
					</td>
				</tr>
				<tr>
					<th>Create Case</th>
					<td>
						@if (isset($inputs['priviledges_createCase']) && $inputs['priviledges_createCase'] == 1)
							Yes
						@else
							No
						@endif
					</td>
				</tr>
			</tbody>
		</table>
		<p class="submit_area">
			{{Form::button('Back to Edit', array('class' => 'common_btn link_group_input'))}}
			{{Form::button('Save', array('class' => 'common_btn group_complete'))}}
		</p>
	{{Form::close()}}
	{{Form::open(['url' => asset('admin/group/input'), 'method' => 'POST', 'class' => 'frm_back'])}}
		{{Form::hidden('btnBack', 'btnBack')}}
	{{Form::close()}}
</div>
@stop