@extends('common.layout')
@section('content')
<script type="text/javascript">
	$(function() {
		//Edit button is pressed during processing
		$('.link_group_edit').click(function(){
			var post_data = $('.frm_group_id').serializeArray();
			var target_elm = $('.frm_group_input');

			$.ajax({
				url: "{{asset('/admin/group/input')}}",
				type: 'POST',
				data: post_data,
				dataType: 'json',
				error: function(){
					alert('I failed to communicate.');
				},
				success: function(res){
					target_elm.empty();
					target_elm.append(res.response);
					target_elm.attr('style', 'display:inline;');
				}
			});
			return false;
		});
	});
</script>
<div class="page_unique">
	<h1 class="page_ttl">Group Detail</h1>
	@if (isset($error_msg))
		<span class="text_alert">{{$error_msg}}</span>
	@else
		<div class="al_l mar_b_10">
			{{HTML::link(asset('admin/group/search'), 'Group Top', array('class' => 'common_btn'))}}
			{{HTML::link(asset('admin/group/input'), 'Edit', array('class' => 'common_btn link_group_edit'))}}
			{{Form::open(['url' => asset('admin/group/input'), 'method' => 'POST', 'class' => 'frm_group_edit'])}}
				{{Form::hidden('GroupID', $group_detail->GroupID, array('class' => 'frm_group_id'))}}
			{{Form::close()}}
		</div>
		<table class="common_table mar_b_20">
			<colgroup>
				<col width="20%">
				<col width="80%">
			</colgroup>
			<tr>
				<th>Group ID</th>
				<td>
					{{$group_detail->GroupID}}
					<span class="font_red">(ID is automatically generated by the system side)</span>
				</td>
			</tr>
			<tr>
				<th>Group Name</th>
				<td>{{$group_detail->GroupName}}</td>
			</tr>
		</table>
	@endif
</div>
@stop