@extends('common.layout')
@section('content')
<script type="text/javascript">
	$(function() {
		//Confirmation button is pressed during processing
		//Cancel button is pressed at the time of processing
		$('.group_cancel').click(function(){
			if (window.confirm('Do you input content but you sure will be destroyed?')){
				var target_elm = $('.frm_group_input');
				target_elm.empty();
			}
			return false;
		});
	});
</script>
{{HTML::script('/js/ajax/group.js')}}
<div class="page_unique">
	<h1 class="page_ttl">{{$title}}</h1>
	@if (isset($error_msg))
		<br><span class="text_alert">{{$error_msg}}</span>
	@else
		{{Form::open(['url' => '', 'method' => 'POST', 'class' => 'frm_group_confirm'])}}
			<table class="common_table mar_b_20">
				<colgroup>
					<col width="20%">
					<col width="80%">
				</colgroup>
				<tr>
					<th>Group ID</th>
					<td>
						{{$inputs['GroupID']}}
						<span class="font_red">(ID is automatically generated by the system side)</span>
						@if (isset($errors) && $errors->has('GroupID'))
							<br><span class="text_alert">{{$errors->first('GroupID')}}</span>
						@endif
					</td>
				</tr>
				<tr>
					<th>Group Name</th>
					<td>
						{{Form::text('GroupName', isset($inputs['GroupName']) ? $inputs['GroupName'] : '', array('placeholder' => 'Group名を入力してください', 'class' => 'common_input_text'))}}
						@if (isset($errors) && $errors->has('GroupName'))
							<br><span class="text_alert">{{$errors->first('GroupName')}}</span>
						@endif
					</td>
				</tr>
			</table>
			<h2 class="con_ttl">Admin Role</h2>
			<table class="common_table al_l">
				<colgroup>
					<col width="20%">
					<col width="80%">
				</colgroup>
				<tbody>
					<tr>
						<th>Create Project</th>
						<td>
							{{Form::checkbox('priviledges.createProject', 1, isset($inputs['priviledges_createProject']) && $inputs['priviledges_createProject'] == 1 ? true : false)}}
							@if (isset($errors) && $errors->has('priviledges.createProject'))
								<br><span class="text_alert">{{$errors->first('priviledges.createProject')}}</span>
							@endif
						</td>
					</tr>
					<tr>
						<th>Create Case</th>
						<td>
							{{Form::checkbox('priviledges.createCase', 1, isset($inputs['priviledges_createCase']) && $inputs['priviledges_createCase'] == 1 ? true : false)}}
							@if (isset($errors) && $errors->has('priviledges.createCase'))
								<br><span class="text_alert">{{$errors->first('priviledges.createCase')}}</span>
							@endif
						</td>
					</tr>
				</tbody>
			</table>
			<p class="submit_area">
				{{Form::button('Cancel', array('class' => 'common_btn group_cancel'))}}
				{{Form::button('Confirmation', array('class' => 'common_btn group_confirm'))}}
			</p>
		{{Form::close()}}
	@endif
</div>
@stop