/*
 * CIRCUS CS Core default configuration file
 *
 * ** DO NOT EDIT THIS FILE DIRECTLY! **
 * Instead, do one of the followings:
 * - Add a file named `local.{json|json5|js}` in this directory
 * - Start the server with --config=<config-file-path>.
 */

'use strict';
var path = require('path');

module.exports = {
	// DICOM file repository is a loader that fetches the content of a DICOM file
	// specified by a series instance UID and an image number.
	"dicomFileRepository": {
		"module": "StaticDicomFileRepository",
		"options": {
			"dataDir": path.join(__dirname, "..", "..", "var", "sample-dicom-data"),
			"useHash": false
		}
	},

	// Logger configurations. By default, we make use of log4js library,
	// so see the documentation for that project.
	"logger": {
		"module": "Log4JsLogger",
		"options": {
			"appenders": [
				{
					"type": "dateFile",
					"filename": path.resolve(__dirname, "../logs/debug.log"),
					"pattern": "-yyyyMMdd.log",
					"alwaysIncludePattern": true
				}
			]
		}
	},
	
	"docker": {
		"socketPath": "/var/run/docker.sock"
	},

	"dicomDumpOptions": {
		"image": "circus/dicom_voxel_dump:1.0",
		"volume_in": "/data/in",
		"volume_out": "/data/out"
	}
};
