parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
env:
  browser: true
  es6: true
  node: true
globals:
  React: true
plugins:
  - react
rules:
  no-console: 'warn'
  quotes: [2, 'single', { avoidEscape: true }]
  jsx-quotes: [2, 'prefer-double']
  padding-line-between-statements:
    - 'error'
    - { blankLine: 'always', prev: 'function', next: 'function' }
    - { blankLine: 'always', prev: 'import', next: '*' }
    - { blankLine: 'any', prev: 'import', next: 'import' }
  no-unused-vars: [2, { argsIgnorePattern: 'props', ignoreRestSiblings: true }]
  'react/prop-types': [0]
  'react/display-name': [0]
  'react/jsx-closing-bracket-location': [2, 'line-aligned']
  no-useless-escape: [0]
  semi: [2, 'always']
  no-var: 'error'
  prefer-const: 'error'
