name: Publish circus-lib to npmjs
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  publish_to_npm:
    defaults:
      run:
        working-directory: ./packages/circus-lib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@utrad-ical'
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Can Publish
        id: canPublish
        run: npx can-npm-publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true
      - name: Publish package
        if: steps.canPublish.outcome != 'failure'
        run: |
          npm ci
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
